pimcore_data_hub:
    configurations:
        ah_packcopy:
            general:
                active: true
                type: dataImporterDataObject
                name: ah_packcopy
                description: ''
                group: ''
                path: null
                modificationDate: 1648797458
                createDate: 1648797301
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: ah_packcopy/upload.import
            interpreterConfig:
                type: xml
                settings:
                    xpath: /PackCopy
                    schema: ''
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '6'
                loadingStrategy:
                    type: path
                    settings:
                        dataSourceIndex: PackCopyHeader
                createLocationStrategy:
                    type: doNotCreate
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangeUnpublishNew
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig: {  }
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
