pimcore_data_hub:
    configurations:
        test_assets:
            general:
                active: true
                type: graphql
                name: test_assets
                description: ''
                group: ''
                sqlObjectCondition: ''
                modificationDate: 1649165226
                path: null
                createDate: 1649164874
            schema:
                queryEntities: {  }
                mutationEntities: {  }
                specialEntities:
                    document:
                        read: false
                        create: false
                        update: false
                        delete: false
                    document_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
                    asset:
                        read: true
                        create: false
                        update: false
                        delete: false
                    asset_folder:
                        read: true
                        create: false
                        update: false
                        delete: false
                    asset_listing:
                        read: true
                        create: false
                        update: false
                        delete: false
                    object_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
            security:
                method: datahub_apikey
                apikey: 0e97b728e396e7a45c74a52f82e09ba3
                skipPermissionCheck: false
            workspaces:
                asset:
                    -
                        read: true
                        cpath: /Heineken
                        create: false
                        update: false
                        delete: false
                        id: extModel719-2
                document: {  }
                object: {  }
            permissions:
                user: {  }
                role: {  }
