pimcore_data_hub:
    configurations:
        test:
            general:
                active: true
                type: graphql
                name: test
                description: ''
                group: ''
                sqlObjectCondition: ''
                modificationDate: 1643656445
                path: null
                createDate: 1643655417
            schema:
                queryEntities:
                    Test:
                        id: Test
                        name: Test
                        columnConfig:
                            columns:
                                -
                                    attributes:
                                        attribute: name
                                        label: name
                                        dataType: input
                                        layout:
                                            fieldtype: input
                                            width: ''
                                            defaultValue: null
                                            queryColumnType: varchar
                                            columnType: varchar
                                            columnLength: 190
                                            regex: ''
                                            unique: false
                                            showCharCount: false
                                            name: name
                                            title: name
                                            tooltip: ''
                                            mandatory: false
                                            noteditable: false
                                            index: false
                                            locked: false
                                            style: ''
                                            permissions: null
                                            datatype: data
                                            relationType: false
                                            invisible: false
                                            visibleGridView: false
                                            visibleSearch: false
                                            defaultValueGenerator: ''
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: description
                                        label: description
                                        dataType: wysiwyg
                                        layout:
                                            fieldtype: wysiwyg
                                            width: ''
                                            height: ''
                                            queryColumnType: longtext
                                            columnType: longtext
                                            toolbarConfig: ''
                                            excludeFromSearchIndex: false
                                            maxCharacters: ''
                                            name: description
                                            title: description
                                            tooltip: ''
                                            mandatory: false
                                            noteditable: false
                                            index: false
                                            locked: false
                                            style: ''
                                            permissions: null
                                            datatype: data
                                            relationType: false
                                            invisible: false
                                            visibleGridView: false
                                            visibleSearch: false
                                    isOperator: false
                mutationEntities: {  }
                specialEntities:
                    document:
                        read: false
                        create: false
                        update: false
                        delete: false
                    document_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
                    asset:
                        read: false
                        create: false
                        update: false
                        delete: false
                    asset_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
                    asset_listing:
                        read: false
                        create: false
                        update: false
                        delete: false
                    object_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
            security:
                method: datahub_apikey
                apikey: ddd4ff1d4461ebbd220a6f0c14976a4a
                skipPermissionCheck: false
            workspaces:
                asset: {  }
                document: {  }
                object: {  }
