doctrine:
  dbal: 
    connections: 
      default: 
        driver: pdo_mysql
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        dbname: '%env(DB_NAME)%'
        mapping_types: { enum: string, bit: boolean }
        server_version: '8.0'
