pimcore:
    documents:
        web_to_print:
            enableInDefaultView: true
            generalTool: pdfreactor
            generalDocumentSaveMode: default
            pdfreactorProtocol: https
            pdfreactorServer: cloud.pdfreactor.com
            pdfreactorServerPort: '443'
            pdfreactorBaseUrl: 'https://demo.pimcore.fun'
            pdfreactorApiKey: ''
            pdfreactorLicence: ''
            pdfreactorEnableLenientHttpsMode: false
            pdfreactorEnableDebugMode: false
            wkhtmltopdfBin: wkhtmltopdf
            wkhtml2pdfOptions:
                print-media-type: ''
                page-size: A4
            wkhtml2pdfHostname: 'http://demo.pimcore.org'
            headlessChromeSettings: ''
